### ISSUE TITLE
Large number of dependencies when installing SimpleInjector.Integration.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector.Integration.AspNetCore#37]
Hi,

when I am installing this library in web api on .net 7.0 additionally many more libs are installed
![image](https://user-images.githubusercontent.com/1914201/236534028-7e221915-1f42-4c3d-973d-917a173e3b2f.png)

I am just curious if it would be more feasible to use FrameworkReference instead of having references to outdated libraries - not sure what you think about it. Potentially how it could look is in draft PR.

Please advise

https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/pull/36

**Comment by dotnetjunkie** [comment]
I'm sorry, I have no experience with `<FrameworkReference>` and its consequences. I have to look into that before I can say anything useful about this.

**Comment by JonasToedter** [comment]
Is there any update on this issue? We have noticed the same behaviour when referencing the package in our .net 6 application. The proposed pull request seems like it would solve the issue well.

**Comment by dotnetjunkie** [comment]
Will incorporate this in the next minor release.

**Comment by Stabzs** [comment]
Is there any traction on the next minor release and/or a potential release date? This is an issue for security scans due to deprecated packages on .NET 6/7 and could lead to us having to migrate off of SimpleInjector if there is an update soon. I'm happy to commit time to look at any outstanding tasks if that would help.

**Comment by dotnetjunkie** [comment]
Hi @Stabzs, the reason I haven't been shipping a new minor release is because there are currently no features for a minor release on the backlog.

Do keep in mind, however, that your security tooling might be giving you false positives. The Simple Injector nuget packages points to the minimal versions of external packages that are compatible with it. This is how NuGet is designed. The minimal version is the version that a package is compatible with. This is hardly ever the version you actually want to use. That these referenced package versions contain security flaws isn't an issue from perspective of the referencing (Simple Injector) NuGet package. What is an issue, however, is if your project actually uses those flawed versions. You should keep all packages up to date. So your security tools should warn if you are actually *using* outdated packages, not if packages are able to use outdated versions of packages, which is something completely different.

You will quickly find that, sticking to your current practice, will spiral into a maintenance nightmare, because dependencies are quicker invalidated than package maintainers (like myself) will be able to keep up. So it's a matter of time before your tools spot another package that has a minimal-version reference of a package with a security issue, while you updated those packages. And btw, this can be again the Simple Injector package in 3 weeks.

To be clear, you should certainly keep your packages up to date and don't use versions of packages that have a security flaws. But on the other hand, there is no security flaw in Simple Injector and a long as you keep its referenced (ASP.NET Core) packages up to date, there is no security risk.

**Comment by Stabzs** [comment]
Hi @dotnetjunkie, thanks for the response.

In normal practices, I'd absolutely agree. You'd be able to pin to updated versions of packages to work around any sort of legacy/obsolete package.

However, in this particular case, Microsoft deprecated some of SimpleInjector.Integration.AspNetCore.Mvc.Core's dependencies several years ago and there _are_ no updated versions to pin to. See

- https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/ 
- https://github.com/dotnet/announcements/issues/217
- https://github.com/dotnet/core/blob/main/release-notes/net-package-deprecation.md
- https://github.com/dotnet/aspnetcore/issues/44457

The issue is that these packages have no correlating targets for .NET Core 3.0 and above and, as a result, any 3rd party libraries need to implement FrameworkReference against anything that isn't a .netstandard compilation target. See

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

In essence, this is what the above draft PR does. It adds multi-targeting to allow .NET "core" targeting class libraries to use the framework reference instead of no-longer-maintained packages.

As a result, I can absolutely sympathize with there being no additional features for a minor release, but this is important enough that I hope you'll consider making an exception to release the above changes, even if they're the only feature in the minor release. There is no upgrade path as is and, if there isn't traction, eventually we'll have to consider alternatives. As a long-time user and admirer of SimpleInjector, I'd really prefer to avoid that.

**Comment by dotnetjunkie** [comment]
Hi @Stabzs,

Thank you for helping me understanding the issue. It took some time for me to read through the links you posted, and go through @AdaskoTheBeAsT's pull request again.

I just pushed version v5.5.0 of the ASP.NET Core integration packages to NuGet. Please check out whether this fixes the issues for you.

**Comment by Stabzs** [comment]
Absolutely, and thank you so much for turning this around so quickly.

I've pulled in the latest package versions and everything looks correct. I'm not seeing any of the extra legacy dependencies. Thank you again!

**Comment by dotnetjunkie** [comment]
> and thank you so much for turning this around so quickly.

That's because you supplied me with some compelling arguments.

Great to hear that it works. Let me know if you find anything.
