### ISSUE TITLE
Registration of Singletons implementing IAsyncDisposable causes exception on shutdown when options.DisposeContainerWithServiceProvider is set

### ISSUE THREAD

**Issue by yaeldekel** [simpleinjector/SimpleInjector.Integration.AspNetCore#4]
When the .Net service provider disposes of the registered instances, it calls DisposeAsync() on the ones that implement IAsyncDisposable and Dispose() on the ones that implement IDisposable. Since ContainerDisposeWrapper is not IAsyncDisposable, it calls Dispose() on the SimpleInjector.Container, which causes an exception if SimpleInjector.Container has any registered instances that are IAsyncDisposable.

**Comment by dotnetjunkie** [comment]
Can you provide me with a full stack trace and possibly a repro?

**Comment by dotnetjunkie** [comment]
And which version of Simple Injector, it's packages, and NET Core are you using?

**Comment by yaeldekel** [comment]
Thanks for the quick response! I am using the nuget package SimpleInjector.Integration.AspNetCore.Mvc.Core version 5.0.0, with .NET Core 3.1. Here is the stack trace:


> "   at SimpleInjector.Scope.DisposeInstancesInReverseOrder(List`1 disposables, Int32 startingAsIndex)\r\n   at SimpleInjector.Scope.DisposeRecursively(Boolean operatingInException)\r\n   at SimpleInjector.Scope.Dispose(Boolean disposing)\r\n   at SimpleInjector.Scope.Dispose()\r\n   at SimpleInjector.ContainerScope.Dispose()\r\n   at SimpleInjector.Container.Dispose(Boolean disposing)\r\n   at SimpleInjector.Container.Dispose()\r\n   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.ContainerDisposeWrapper.Dispose()\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync() in /_/src/DependencyInjection/DI/src/ServiceLookup/ServiceProviderEngineScope.cs:line 93\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151\r\n   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/ValueTaskAwaiter.cs:line 47\r\n   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__12.MoveNext() in /_/src/Hosting/Hosting/src/Internal/Host.cs:line 111\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151\r\n   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/ValueTaskAwaiter.cs:line 47\r\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext() in /_/src/Hosting/Abstractions/src/HostingAbstractionsHostExtensions.cs:line 70\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 107\r\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) in /_/src/Hosting/Abstractions/src/HostingAbstractionsHostExtensions.cs:line 50\r\n   at Microsoft.Azure.VideoIndexer.Map.Workers.AcousticEventDetection.WebApi.Program.Main(String[] args) in C:\\Users\\yaeld\\source\\repos\\WebApplication2\\WebApplication2\\Program.cs:line 44"


I am attaching a solution containing a repro.

[WebApplication2.zip](https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/files/5434349/WebApplication2.zip)

**Comment by dotnetjunkie** [comment]
Ah yes, I see the problem. In v5, we forgot to implement IAsynDisposable on the ContainerDisposeWrapper of the SimpleInjector.Integration.ServiceCollection package. This is a bug, which I shall fix.

**Comment by dotnetjunkie** [comment]
This bug was fixed in [SimpleInjector.Integration.ServiceCollection v5.0.2](https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/releases/tag/sc_5.0.2).

**Comment by yaeldekel** [comment]
Hi @dotnetjunkie ,
Is it possible that this bug was reintroduced somewhere between version 5.0.2 and version 5.2?
Thanks!

**Comment by dotnetjunkie** [comment]
That would be unfortunate if it did. Can you provide a repro with v5.2?

**Comment by yaeldekel** [comment]
[WebApplication2.zip](https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/files/5750703/WebApplication2.zip)
This is similar to the repro I attached above, but this time I use three nugets:

SimpleInjector 5.2
SimpleInjector.Integration.AspNetCore.Mvc.Core 5.0
SimpleInjector.Integration.ServiceCollection

When I use version 5.0.2 of SimpleInjector.Integration.ServiceCollection, it works perfectly, but when I upgrade to version 5.2 of SimpleInjector.Integration.ServiceCollection I get this error:

>
'Simple Injector was configured to be disposed of together with the application's ServiceProviderEngineScope. This configuration is not suited for asynchronous disposal. The Simple Injector Container, however, contains a Singleton that implements IAsyncDisposable, which cannot be disposed of synchronously. To fix this problem, configure Simple Injector by setting SimpleInjectorAddOptions.DisposeContainerWithServiceProvider to false and manually call 'await Container.DisposeContainerAsync()' at application shutdown. e.g.:
services.AddSimpleInjector(container, options => { options.DisposeContainerWithServiceProvider = false; }). Foo only implements IAsyncDisposable, but not IDisposable. Make sure to call Container.DisposeAsync() instead of Container.Dispose().'

(This is different than the original error message I got).

This might be a weird issue with the nugets, because if I upgrade SimpleInjector.Integration.AspNetCore.Mvc.Core to version 5.2 as well, the error goes away.

**Comment by dotnetjunkie** [comment]
Thanks for the quick repro. For completeness, can you post the full stack trace?

**Comment by yaeldekel** [comment]
Sure:

>    at SimpleInjector.SimpleInjectorServiceCollectionExtensions.ContainerDisposeWrapper.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebApplication2\WebApplication2\Program.cs:line 44

**Comment by dotnetjunkie** [comment]
@yaeldekel,

If you upgrade `SimpleInjector.Integration.AspNetCore.Mvc.Core` from 5.0.0 to 5.2.0, your problems should dissapear.

**Comment by dotnetjunkie** [comment]
The changes with regards to `IAsyncDisposable` forced changes in multiple parts of Simple Injector, which means you have to upgrade everything to the latest version.

**Comment by yaeldekel** [comment]
I see. I suspected it was a version mismatch issue. Thanks for your quick assistance!

**Comment by laithhisham** [comment]
@dotnetjunkie 
We are facing a similar issue on service shutdown when having a registered instance that implements IAsyncDisposable.
We get the following exception

"""
Simple Injector was configured to be disposed of together with the application's ServiceProvider. This configuration is not suited for asynchronous disposal. The Simple Injector Container, however, contains a Singleton that implements IAsyncDisposable, which cannot be disposed of synchronously. To fix this problem, configure Simple Injector by setting SimpleInjectorAddOptions.DisposeContainerWithServiceProvider to false and manually call 'await Container.DisposeContainerAsync()' at application shutdown. e.g.:
services.AddSimpleInjector(container, options => { options.DisposeContainerWithServiceProvider = false; }). {type} only implements IAsyncDisposable, but not IDisposable. Make sure to call Container.DisposeAsync() instead of Container.Dispose()
"""

we are using version 5.4.0 of the following packages:
SimpleInjector
SimpleInjector.Integration.AspNetCore
SimpleInjector.Integration.GenericHost
SimpleInjector.Integration.AspNetCore.Mvc.Core

could it be that the issue was reintroduced again in newer versions?

**Comment by dotnetjunkie** [comment]
Hi @laithhisham, can you create a repro, ideally as Github repo?

**Comment by laithhisham** [comment]
@dotnetjunkie 
sure, uploaded a very simple repro of the issue here: https://github.com/laithhisham/SimpleInjectorDisposeRepro
after building and running the app, once attempting to trigger shutdown with Ctrl+C you can see the exception reproduced.

These are the full details I got there

System.InvalidOperationException
  HResult=0x80131509
  Message=Simple Injector was configured to be disposed of together with the application's ServiceProvider. This configuration is not suited for asynchronous disposal. The Simple Injector Container, however, contains a Singleton that implements IAsyncDisposable, which cannot be disposed of synchronously. To fix this problem, configure Simple Injector by setting SimpleInjectorAddOptions.DisposeContainerWithServiceProvider to false and manually call 'await Container.DisposeContainerAsync()' at application shutdown. e.g.:
services.AddSimpleInjector(container, options => { options.DisposeContainerWithServiceProvider = false; }). TestDisposableAsyncClass only implements IAsyncDisposable, but not IDisposable. Make sure to call Container.DisposeAsync() instead of Container.Dispose().
  Source=SimpleInjector.Integration.ServiceCollection
  StackTrace:
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.ContainerDisposeWrapper.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.Internal.Host.<<DisposeAsync>g__DisposeAsync|16_0>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__16.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\lahisham.MIDDLEEAST\source\repos\SimpleInjectorDisposeRepro\SimpleInjectorDisposeReproHostedService\Program.cs:line 21
   at Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    SimpleInjector.Scope.ThrowTypeOnlyImplementsIAsyncDisposable(object)
    SimpleInjector.Scope.DisposeInstancesInReverseOrder(System.Collections.Generic.List<object>, int)
    SimpleInjector.Scope.DisposeRecursively(bool)
    SimpleInjector.Scope.Dispose(bool)
    SimpleInjector.Container.Dispose(bool)
    SimpleInjector.SimpleInjectorServiceCollectionExtensions.ContainerDisposeWrapper.Dispose()

Inner Exception 1:
InvalidOperationException: TestDisposableAsyncClass only implements IAsyncDisposable, but not IDisposable. Make sure to call Container.DisposeAsync() instead of Container.Dispose().

**Comment by dotnetjunkie** [comment]
Hi @laithhisham,

The error you are getting is intentional. While the internal `ContainerDisposeWrapper` initially implemented `IAsyncDisposable`, because we had to remove the dependency from the ServiceCollection package to the Microsoft.Bcl.AsyncInterfaces package, as explained [here](https://blog.simpleinjector.org/2020/12/the-tale-of-the-async-interfaces/). One of the breaking changes this introduced was the disability for the container to be automatically asynchronously disposed of at application shutdown. The error message was (re)introduced to explain how to fix this. This means that, if you follow the guidance in that message, you will be able to gracefully shutdown the application.

In your case this basically means adding two lines of code. Here's your `Program.cs` with the changed lines annotated:

``` c#
var container = new Container();

var host = Host.CreateDefaultBuilder()
    .ConfigureServices(ConfigureServices)
    .UseConsoleLifetime()
    .Build()
    .UseSimpleInjector(container);

container.Verify();

var testDisposable = container.GetInstance<TestDisposableAsyncClass>();
Console.WriteLine(testDisposable.TestMethod());

var cancellationToken = new CancellationTokenSource();

await host.RunAsync(cancellationToken.Token);

await container.DisposeAsync(); // ADDED: Dispose Simple Injector

void ConfigureServices(IServiceCollection services)
{
    services.AddSimpleInjector(container, options => 
    {
        options.DisposeContainerWithServiceProvider = false; // ADDED: Set dispose to manual mode
    });
    container.RegisterSingleton<TestDisposableAsyncClass, TestDisposableAsyncClass>();
}
```

**Comment by laithhisham** [comment]
@dotnetjunkie 
Thanks a lot for the explanation and the interesting blog!
We already made that change, I was just wondering if I missed something and there was some way to configure it internally.
